REAL_TIME_RIDE_STATUS__IDLE = 'idle'
REAL_TIME_RIDE_STATUS__IN_QUEUE = 'inQueue'
REAL_TIME_RIDE_STATUS__PROCESSING = 'processing'
REAL_TIME_RIDE_STATUS__ON_RIDE = 'onRide'

REDIS_KEYS__REAL_TIME_RIDE_STATUS = 'realTimeRideStatus'
REDIS_KEYS__REAL_TIME_RIDE_REQUEST = 'realTimeRideRequest'
REDIS_KEYS__DRIVER_LOCATION = 'driverLocation'